spring:
  messages:
    basename: i18n/messages
  # rabbitmq 配置
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest
    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
    publisher-confirm-type: correlated
    #保证交换机能把消息推送到队列中
    publisher-returns: true
    virtual-host: /
    #这个配置是保证消费者会消费消息，手动确认
#    listener:
#      simple:
#        acknowledge-mode: manual
#    template:
#      mandatory: true
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  200MB
      # 设置总上传的文件大小
      max-request-size:  500MB
  # redis 配置
  redis:
    # 地址 127.0.0.1
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码 正式环境密码 octV@123
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池的最大数据库连接数
        max-active: 10
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# elasticsearch配置
  elasticsearch:
    rest:
      # es访问地址,多个用英文逗号隔开
      uris: http://43.138.196.197:9200
      connection-timeout: 10 #连接超时时间,单位是s
      read-timeout: 5 # 读超时时间,单位是s
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.octv.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatisMapper/*.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatisMapper/config/mybatis-config.xml

minio:
  # minio配置是自定义的配置，注意：一定加http://
  endpoint: http://114.132.77.125:9010
  accessKey: admin
  secretKey: wsh122966
  bucketName: im-server

# 聊天服务配置
octv:
  im-chat-server:
    port: 7988
    ipAddress: 127.0.0.1
    intervalMillis: 9000 #间隔多少秒没收到服务端没收到心跳则判定该channel 已经挂了
    open-cluster: true  #是否集群
    scheduled:
      check-active: "*/60 * * * * ?"  #多久检查一次存活的channel
      heart-beat: "*/30 * * * * ?"    #向连接的客户端发送心跳


